modLoader="javafml"
loaderVersion="[43,)"
license="Creative Commons Attribution-NonCommercial 3.0"

[[mods]]
modId="shineals_end_update"
version="1.0.0"
displayName="ShiNeaL's End Update"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="ShinyDragon96, TgwCreeper, GlitchedMastery, MCreator"

[[dependencies.shineals_end_update]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"



[[dependencies.shineals_end_update]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

